const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,ACCESS_TOKEN=process.env.ACCESS_TOKEN||"cambia-este-link-secreto",ADMIN_PIN=process.env.ADMIN_PIN||"1234";
const DATA_DIR=path.join(__dirname,"data"),DATA_FILE=path.join(DATA_DIR,"staff.json");fs.mkdirSync(DATA_DIR,{recursive:true});
const RANKS=["SDP","SP","SE","MOD","MOD+","MOD++","ADM","ADM+","ADM++"],DAYS=["sabado","domingo","lunes","martes","miercoles","jueves","viernes"];
function blankDays(){return Object.fromEntries(DAYS.map(d=>[d,{hours:0,status:"normal"}]))}
function member(name,rank,hours){const days=blankDays();days.sabado.hours=hours;return{id:crypto.randomUUID(),name,rank,days}}
const defaultData={settings:{serverName:"IMPERIO RP",weekLabel:"Semana actual",statScale:200,targets:{SDP:8,SP:8,SE:10,MOD:10,"MOD+":10,"MOD++":12,ADM:12,"ADM+":12,"ADM++":14},colors:{SDP:"#149eea",SP:"#149eea",SE:"#149eea",MOD:"#8b4dff","MOD+":"#8b4dff","MOD++":"#8b4dff",ADM:"#ff4e57","ADM+":"#ff4e57","ADM++":"#ff4e57"},permissions:{OWNER:{"Editar horas":true,"Agregar/eliminar Staff":true,"Cambiar colores":true,"Gestionar accesos":true,"Ver historial":true},EDITOR:{"Editar horas":true,"Agregar/eliminar Staff":true,"Cambiar colores":false,"Gestionar accesos":false,"Ver historial":true},VIEWER:{"Editar horas":false,"Agregar/eliminar Staff":false,"Cambiar colores":false,"Gestionar accesos":false,"Ver historial":true}},access:[{id:crypto.randomUUID(),name:"Matí",role:"OWNER",token:"cambia-este-link-secreto"}]},staff:[member("Matí","ADM++",0),member("Raul","ADM+",0),member("Mono","ADM",0),member("Tomi","MOD++",0),member("Luca","MOD+",0),member("Facha","MOD",0),member("Fran","SDP",0),member("Niko","SP",0),member("Jere","SE",0)]};
if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,JSON.stringify(defaultData,null,2));
function read(){const d=JSON.parse(fs.readFileSync(DATA_FILE,"utf8"));d.settings.colors=d.settings.colors||defaultData.settings.colors;d.settings.permissions=d.settings.permissions||defaultData.settings.permissions;d.settings.access=d.settings.access||defaultData.settings.access;d.staff.forEach(m=>{m.days=m.days||blankDays();DAYS.forEach(x=>{m.days[x]=m.days[x]||{hours:0,status:"normal"}})});return d}
function write(d){fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2))}
function validToken(t){if(typeof t!=="string")return false;const a=Buffer.from(t),b=Buffer.from(ACCESS_TOKEN);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function auth(req,res,next){const token=req.cookies?.imperio_access||req.headers["x-access-token"];if(!token)return res.status(401).json({error:"No autorizado"});const d=read();const u=d.settings.access.find(x=>x.token===token);if(!u&&!validToken(token))return res.status(401).json({error:"No autorizado"});req.user=u||{name:"Matí",role:"OWNER",token};next()}
function owner(req,res,next){if(req.user.role!=="OWNER")return res.status(403).json({error:"Solo los Owners pueden hacer esto"});next()}
app.use(express.json({limit:"100kb"}));app.use((req,_res,next)=>{req.cookies={};(req.headers.cookie||"").split(";").forEach(p=>{const i=p.indexOf("=");if(i>-1)req.cookies[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});next()});
app.get("/panel/:token",(req,res)=>{if(!validToken(req.params.token)&&!read().settings.access.some(x=>x.token===req.params.token))return res.status(404).send("Página no encontrada");res.setHeader("Set-Cookie",`imperio_access=${encodeURIComponent(req.params.token)}; HttpOnly; SameSite=Lax; ${process.env.NODE_ENV==="production"?"Secure; ":""}Max-Age=2592000; Path=/`);res.sendFile(path.join(__dirname,"public","index.html"))});
app.use("/assets",express.static(path.join(__dirname,"public")));
app.get("/api/data",auth,(req,res)=>{const d=read();d.currentUser={name:req.user.name,role:req.user.role};res.json(d)});
app.put("/api/staff/:id",auth,(req,res)=>{if(!["OWNER","EDITOR"].includes(req.user.role))return res.status(403).json({error:"Tu acceso es de solo lectura"});const d=read(),m=d.staff.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:"Staff no encontrado"});if(typeof req.body.name==="string")m.name=req.body.name.trim().slice(0,60);if(typeof req.body.rank==="string"&&d.settings.targets[req.body.rank]!=null)m.rank=req.body.rank;write(d);res.json(m)});
app.post("/api/staff",auth,(req,res)=>{if(!["OWNER","EDITOR"].includes(req.user.role))return res.status(403).json({error:"Sin permiso"});const d=read(),{name,rank}=req.body;if(!name||!d.settings.targets[rank]&&d.settings.targets[rank]!==0)return res.status(400).json({error:"Nombre y rango válidos requeridos"});const m=member(String(name).trim().slice(0,60),rank,0);d.staff.push(m);write(d);res.status(201).json(m)});
app.delete("/api/staff/:id",auth,(req,res)=>{if(req.user.role!=="OWNER")return res.status(403).json({error:"Solo Owner"});const d=read(),n=d.staff.length;d.staff=d.staff.filter(x=>x.id!==req.params.id);if(n===d.staff.length)return res.status(404).json({error:"Staff no encontrado"});write(d);res.json({ok:true})});
app.put("/api/staff/:id/day",auth,(req,res)=>{if(!["OWNER","EDITOR"].includes(req.user.role))return res.status(403).json({error:"Tu acceso es de solo lectura"});const d=read(),m=d.staff.find(x=>x.id===req.params.id),day=req.body.day;if(!m||!DAYS.includes(day))return res.status(400).json({error:"Datos inválidos"});m.days[day]=m.days[day]||{hours:0,status:"normal"};if(req.body.hours!==undefined)m.days[day].hours=Math.max(0,Number(req.body.hours)||0);if(["normal","inactive","justified"].includes(req.body.status))m.days[day].status=req.body.status;write(d);res.json(m)});
app.put("/api/settings",auth,owner,(req,res)=>{if(req.body.adminPin!==ADMIN_PIN)return res.status(403).json({error:"PIN de Owner incorrecto"});const d=read();for(const [r,v] of Object.entries(req.body.targets||{}))if(d.settings.targets[r]!=null)d.settings.targets[r]=Math.max(0,Number(v)||0);write(d);res.json(d.settings)});
app.put("/api/colors",auth,owner,(req,res)=>{if(req.body.adminPin!==ADMIN_PIN)return res.status(403).json({error:"PIN de Owner incorrecto"});const d=read();d.settings.colors={...d.settings.colors,...req.body.colors};write(d);res.json(d.settings.colors)});
app.put("/api/permissions",auth,owner,(req,res)=>{if(req.body.adminPin!==ADMIN_PIN)return res.status(403).json({error:"PIN de Owner incorrecto"});const d=read();d.settings.permissions=req.body.permissions;write(d);res.json(d.settings.permissions)});
app.post("/api/access",auth,owner,(req,res)=>{if(req.body.adminPin!==ADMIN_PIN)return res.status(403).json({error:"PIN de Owner incorrecto"});const d=read(),role=String(req.body.role||"").toUpperCase();if(!["OWNER","EDITOR","VIEWER"].includes(role)||!req.body.name||!req.body.token)return res.status(400).json({error:"Datos inválidos"});if(d.settings.access.some(x=>x.token===req.body.token))return res.status(400).json({error:"Ese token ya existe"});const x={id:crypto.randomUUID(),name:String(req.body.name).trim().slice(0,60),role,token:String(req.body.token).trim()};d.settings.access.push(x);write(d);res.status(201).json(x)});
app.delete("/api/access/:id",auth,owner,(req,res)=>{if(req.body.adminPin!==ADMIN_PIN)return res.status(403).json({error:"PIN de Owner incorrecto"});const d=read();d.settings.access=d.settings.access.filter(x=>x.id!==req.params.id);write(d);res.json({ok:true})});
app.listen(PORT,()=>console.log(`IMPERIO RP Staff Horas: http://localhost:${PORT}/panel/${ACCESS_TOKEN}`));