const express=require("express");const session=require("express-session");const helmet=require("helmet");const rateLimit=require("express-rate-limit");const fs=require("fs");const path=require("path");const crypto=require("crypto");
const app=express(),PORT=process.env.PORT||8080,DATA_DIR=process.env.DATA_DIR||path.join(__dirname,"data"),DB_FILE=path.join(DATA_DIR,"db.json");
const OWNER_EMAIL=(process.env.OWNER_EMAIL||"").trim().toLowerCase(),SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString("hex"),BASE_URL=(process.env.BASE_URL||"").replace(/\/+$/,"");fs.mkdirSync(DATA_DIR,{recursive:true});
const empty={users:[],hours:{},logs:[]};let db;try{db=fs.existsSync(DB_FILE)?JSON.parse(fs.readFileSync(DB_FILE,"utf8")):structuredClone(empty)}catch{db=structuredClone(empty)}
function save(){let t=DB_FILE+".tmp";fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DB_FILE)}function id(){return crypto.randomBytes(8).toString("hex")}
function log(a,d,u){db.logs.unshift({id:id(),at:new Date().toISOString(),action:a,details:d,actor:u?.email||"system"});db.logs=db.logs.slice(0,500);save()}
function rate(r){if(["ADM","ADM+","ADM++"].includes(r))return 2000000;if(["MOD","MOD+","MOD++"].includes(r))return 1500000;return 1000000}
function owner(req){return req.session.user?.accessRole==="OWNER"}function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:"No autenticado"});next()}
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:"200kb"}));app.use(session({secret:SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000}}));app.use("/api",rateLimit({windowMs:60000,limit:180}));app.use(express.static(path.join(__dirname,"public")));
app.get("/auth/google",(req,res)=>{if(!process.env.GOOGLE_CLIENT_ID)return res.status(500).send("Falta GOOGLE_CLIENT_ID.");let red=(BASE_URL||req.protocol+"://"+req.get("host"))+"/auth/google/callback";let p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:red,response_type:"code",scope:"openid email profile",access_type:"offline",prompt:"select_account"});res.redirect("https://accounts.google.com/o/oauth2/v2/auth?"+p)});
app.get("/auth/google/callback",async(req,res)=>{try{let red=(BASE_URL||req.protocol+"://"+req.get("host"))+"/auth/google/callback";let tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code:req.query.code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:red,grant_type:"authorization_code"})});let tok=await tr.json();if(!tok.access_token)return res.status(401).send("Google no autorizó.");let ir=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{Authorization:"Bearer "+tok.access_token}}),info=await ir.json(),email=String(info.email||"").toLowerCase();let u=db.users.find(x=>x.email===email);if(!u&&email===OWNER_EMAIL){u={id:id(),name:info.name||"OWNER",email,accessRole:"OWNER",staffRank:"ADM++",notes:"",createdAt:new Date().toISOString()};db.users.push(u);save()}if(!u)return res.status(403).send("Tu cuenta no tiene acceso.");req.session.user={...u};res.redirect("/")}catch(e){console.error(e);res.status(500).send("Error de autenticación.")}});
app.post("/auth/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get("/api/me",(req,res)=>res.json({user:req.session.user||null}));
app.get("/api/bootstrap",auth,(req,res)=>res.json({user:req.session.user,users:db.users,hours:db.hours,rates:{HIGH:2000000,MID:1500000,LOW:1000000},timeZone:process.env.APP_TIMEZONE||"America/Argentina/Buenos_Aires"}));
app.post("/api/users",auth,(req,res)=>{if(!owner(req))return res.status(403).json({error:"Solo OWNER"});let name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),rank=["ADM","ADM+","ADM++","MOD","MOD+","MOD++","SDP","SP","SE"].includes(req.body.staffRank)?req.body.staffRank:"SDP";if(!name||!email)return res.status(400).json({error:"Nombre y email son obligatorios"});if(db.users.some(u=>u.email===email))return res.status(409).json({error:"Ese email ya existe"});let u={id:id(),name,email,accessRole:["OWNER","EDITOR","VIEWER"].includes(req.body.accessRole)?req.body.accessRole:"EDITOR",staffRank,notes:String(req.body.notes||""),createdAt:new Date().toISOString()};db.users.push(u);save();log("user_created","Creado "+email,req.session.user);res.json(u)});
app.patch("/api/users/:id",auth,(req,res)=>{if(!owner(req))return res.status(403).json({error:"Solo OWNER"});let u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:"No encontrado"});for(let k of ["name","email","notes"])if(req.body[k]!==undefined)u[k]=String(req.body[k]).trim();if(["OWNER","EDITOR","VIEWER"].includes(req.body.accessRole))u.accessRole=req.body.accessRole;if(["ADM","ADM+","ADM++","MOD","MOD+","MOD++","SDP","SP","SE"].includes(req.body.staffRank))u.staffRank=req.body.staffRank;save();if(req.session.user.id===u.id)req.session.user={...u};res.json(u)});
app.delete("/api/users/:id",auth,(req,res)=>{if(!owner(req))return res.status(403).json({error:"Solo OWNER"});let i=db.users.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:"No encontrado"});let u=db.users.splice(i,1)[0];save();log("user_deleted","Eliminado "+u.email,req.session.user);res.json({ok:true})});
app.patch("/api/hours/:userId/:date",auth,(req,res)=>{if(req.session.user.accessRole==="VIEWER")return res.status(403).json({error:"Sin permisos"});let u=db.users.find(x=>x.id===req.params.userId);if(!u)return res.status(404).json({error:"Usuario no encontrado"});let v=String(req.body.value||"0:00");if(!/^\d{1,4}:\d{1,2}$/.test(v))return res.status(400).json({error:"Formato H:MM"});let [h,m]=v.split(":").map(Number);if(m>99)return res.status(400).json({error:"Minutos 00 a 99"});let status=["normal","inactive","justified","void"].includes(req.body.status)?req.body.status:"normal";db.hours[u.id+":"+req.params.date]={value:h+":"+String(m).padStart(2,"0"),status};save();res.json(db.hours[u.id+":"+req.params.date])});
app.get("/api/logs",auth,(req,res)=>owner(req)?res.json(db.logs):res.status(403).json({error:"Solo OWNER"}));app.get("/api/export",auth,(req,res)=>{if(!owner(req))return res.status(403).json({error:"Solo OWNER"});res.setHeader("Content-Disposition",'attachment; filename="imperio-rp-respaldo.json"');res.json(db)});
app.get("*",(req,res,next)=>req.path.startsWith("/api/")||req.path.startsWith("/auth/")?next():res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("Imperio RP Staff Horas running on "+PORT));
